apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      bu: finance
      app: nginx
      tier: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        bu: finance
        app: nginx
        tier: prod
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      bu: it
      app: nginx
      tier: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        bu: it
        app: nginx
        tier: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  ports:
    - port: 80
      targetPort: 9876
  selector:
      bu: finance
      app: nginx
      tier: prod
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  ports:
    - port: 80
      targetPort: 9876
  selector:
      bu: it
      app: nginx
      tier: dev