apiVersion: v1
kind: Pod
metadata:
  name: controlschedrun
spec:
  containers:
  - command:
    - sleep
    - "2000"
    image: busybox:1.35.0
    imagePullPolicy: IfNotPresent
    name: controlschedrun
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
    operator: Equal
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
