apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata: 
  namespace: default  
  name: rolebinding1 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: Role 
  name: role1
subjects:
- apiGroup: rbac.authorization.k8s.io    
  kind: User 
  name: curtis