apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny
  namespace: admin
spec:
  podSelector: 
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny
  namespace: frontend
spec:
  podSelector: 
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny
  namespace: backend
spec:
  podSelector: 
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}