apiVersion: v1
kind: Pod
metadata:
  name: stress-3
spec:
  containers:
  - name: cpu-demo-ctr
    image: curtisab/stress:v1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "0.5"
    args:
    - -cpus
    - "1"