apiVersion: v1
kind: Pod
metadata:
  name: manual
spec:
  containers:
  -  image: nginx:1.14.2
     imagePullPolicy: IfNotPresent
     name: nginx
     resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeName: replaceMe
