apiVersion: v1
kind: Pod
metadata:
  name: masterSchedRun
spec:
  containers:
  - command:
    - sleep
    - "2000"
    image: busybox
    name: masterSchedRun
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    operator: Equal
