apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-localhost
spec:
  ingressClassName: nginx
  rules:
  - host: whoami.localdev.me
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /
        pathType: Prefix