---
apiVersion: v1
kind: Pod
metadata:
  name: mem-stress
  namespace: default
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 500M
    - --vm-hang
    - "1"
    image: polinux/stress:1.0.4
    imagePullPolicy: IfNotPresent
    resources:
        limits:
          memory: 800Mi
          cpu: "1"
        requests:
          memory: 500Mi
    command:
      - stress
    name: mem-stress
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: default
spec:
  containers:
  - args:
    - -cpus
    - "1"
    image: vish/stress:latest
    imagePullPolicy: IfNotPresent
    resources:
        limits:
          cpu: "1"
    name: cpu-stress
